// GENERATED by tools/update_licenses.py. Do not edit by hand: re-run the script after
// any dependency change (see CLAUDE.md).
package com.malikfikret.ttlvpn.ui

import com.malikfikret.ttlvpn.R

internal enum class LicenseSection { App, Engine, Android }

internal data class OssComponent(
    val section: LicenseSection,
    val name: String,
    val license: String, // SPDX identifier
    val copyright: String,
    val detail: String?,
    val text: Int, // R.raw resource with the full license text, verbatim (English)
)

internal val OSS_COMPONENTS = listOf(
    OssComponent(LicenseSection.App, "TTL VPN", "GPL-3.0", "© 2026 Malik Fikret", null, R.raw.license_gpl_3_0_b4d7662b),
    OssComponent(LicenseSection.Engine, "tun2socks", "MIT", "Copyright (c) 2019 Jason Lyu", null, R.raw.license_mit_cb04bb8e),
    OssComponent(LicenseSection.Engine, "gVisor", "Apache-2.0", "Copyright The gVisor Authors", null, R.raw.license_apache_2_0_9b5cdb8d),
    OssComponent(LicenseSection.Engine, "Go standard library and runtime", "BSD-3-Clause", "Copyright 2009 The Go Authors.", null, R.raw.license_bsd_3_clause_6aeb85c6),
    OssComponent(LicenseSection.Engine, "github.com/ajg/form", "BSD-3-Clause", "Copyright (c) 2014 Alvaro J. Genial. All rights reserved.", null, R.raw.license_bsd_3_clause_a3e6e78d),
    OssComponent(LicenseSection.Engine, "github.com/docker/go-units", "Apache-2.0", "Copyright 2015 Docker, Inc.", null, R.raw.license_apache_2_0_3e0c6df6),
    OssComponent(LicenseSection.Engine, "github.com/go-chi/chi/v5", "MIT", "Copyright (c) 2015-present Peter Kieltyka (https://github.com/pkieltyka), Google Inc.", null, R.raw.license_mit_134abc2f),
    OssComponent(LicenseSection.Engine, "github.com/go-chi/cors", "MIT", "Copyright (c) 2014 Olivier Poitrey <rs@dailymotion.com>", null, R.raw.license_mit_65e0b43f),
    OssComponent(LicenseSection.Engine, "github.com/go-chi/render", "MIT", "Copyright (c) 2016-Present https://github.com/go-chi authors", null, R.raw.license_mit_cf407e0f),
    OssComponent(LicenseSection.Engine, "github.com/go-gost/relay", "MIT", "Copyright (c) 2016 ginuerzh", null, R.raw.license_mit_4bc157f2),
    OssComponent(LicenseSection.Engine, "google/btree", "Apache-2.0", "Copyright Google Inc.", null, R.raw.license_apache_2_0_be86a8dd),
    OssComponent(LicenseSection.Engine, "google/shlex", "Apache-2.0", "Copyright Google Inc.", null, R.raw.license_apache_2_0_be86a8dd),
    OssComponent(LicenseSection.Engine, "github.com/google/uuid", "BSD-3-Clause", "Copyright (c) 2009,2014 Google Inc. All rights reserved.", null, R.raw.license_bsd_3_clause_08021ae7),
    OssComponent(LicenseSection.Engine, "github.com/gorilla/schema", "BSD-3-Clause", "Copyright (c) 2023 The Gorilla Authors. All rights reserved.", null, R.raw.license_bsd_3_clause_3bf9ba7c),
    OssComponent(LicenseSection.Engine, "github.com/gorilla/websocket", "BSD-2-Clause", "Copyright (c) 2013 The Gorilla WebSocket Authors. All rights reserved.", null, R.raw.license_bsd_2_clause_307711a6),
    OssComponent(LicenseSection.Engine, "go.uber.org/atomic", "MIT", "Copyright (c) 2016 Uber Technologies, Inc.", null, R.raw.license_mit_fa2149c3),
    OssComponent(LicenseSection.Engine, "go.uber.org/multierr", "MIT", "Copyright (c) 2017-2021 Uber Technologies, Inc.", null, R.raw.license_mit_6deb0a32),
    OssComponent(LicenseSection.Engine, "go.uber.org/zap", "MIT", "Copyright (c) 2016-2024 Uber Technologies, Inc.", null, R.raw.license_mit_f09afb4a),
    OssComponent(LicenseSection.Engine, "golang.org/x/crypto", "BSD-3-Clause", "Copyright 2009 The Go Authors.", null, R.raw.license_bsd_3_clause_6aeb85c6),
    OssComponent(LicenseSection.Engine, "golang.org/x/exp", "BSD-3-Clause", "Copyright 2009 The Go Authors.", null, R.raw.license_bsd_3_clause_6aeb85c6),
    OssComponent(LicenseSection.Engine, "golang.org/x/mobile", "BSD-3-Clause", "Copyright 2009 The Go Authors.", null, R.raw.license_bsd_3_clause_6aeb85c6),
    OssComponent(LicenseSection.Engine, "golang.org/x/sys", "BSD-3-Clause", "Copyright 2009 The Go Authors.", null, R.raw.license_bsd_3_clause_6aeb85c6),
    OssComponent(LicenseSection.Engine, "golang.org/x/time", "BSD-3-Clause", "Copyright 2009 The Go Authors.", null, R.raw.license_bsd_3_clause_6aeb85c6),
    OssComponent(LicenseSection.Android, "AndroidX / Jetpack", "Apache-2.0", "Copyright The Android Open Source Project", "Activity, Compose (Runtime, UI, Foundation, Animation, Material 3), Core, DataStore, Lifecycle, Navigation Event, SavedState, Startup, Profile Installer, Tracing, Window and their support libraries", R.raw.license_apache_2_0_be86a8dd),
    OssComponent(LicenseSection.Android, "Kotlin standard library", "Apache-2.0", "Copyright JetBrains s.r.o. and Kotlin Programming Language contributors", null, R.raw.license_apache_2_0_be86a8dd),
    OssComponent(LicenseSection.Android, "kotlinx.coroutines", "Apache-2.0", "Copyright JetBrains s.r.o. and contributors", null, R.raw.license_apache_2_0_be86a8dd),
    OssComponent(LicenseSection.Android, "kotlinx.serialization", "Apache-2.0", "Copyright JetBrains s.r.o. and contributors", null, R.raw.license_apache_2_0_be86a8dd),
    OssComponent(LicenseSection.Android, "Okio", "Apache-2.0", "Copyright Square, Inc.", null, R.raw.license_apache_2_0_be86a8dd),
    OssComponent(LicenseSection.Android, "JetBrains Java Annotations", "Apache-2.0", "Copyright JetBrains s.r.o.", null, R.raw.license_apache_2_0_be86a8dd),
    OssComponent(LicenseSection.Android, "JSpecify", "Apache-2.0", "Copyright The JSpecify Authors", null, R.raw.license_apache_2_0_be86a8dd),
    OssComponent(LicenseSection.Android, "Guava ListenableFuture", "Apache-2.0", "Copyright The Guava Authors", null, R.raw.license_apache_2_0_be86a8dd),
)
