package com.malikfikret.ttlvpn.ui.theme

import androidx.compose.ui.graphics.Color

// Every Material 3 role is set explicitly: any role left out falls back to the
// baseline purple palette (that's where the lavender cards came from).

// Light: neutral near-white base, deep teal accent
val PrimaryLight = Color(0xFF00605F)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFC4ECEA)
val OnPrimaryContainerLight = Color(0xFF00201F)
val SecondaryLight = Color(0xFF4A6362)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFCCE8E6)
val OnSecondaryContainerLight = Color(0xFF051F1F)
val TertiaryLight = Color(0xFF3F6377)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFC3E8FF)
val OnTertiaryContainerLight = Color(0xFF001E2C)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF410002)
val BackgroundLight = Color(0xFFF7F9F9)
val OnBackgroundLight = Color(0xFF171D1D)
val SurfaceLight = Color(0xFFF7F9F9)
val OnSurfaceLight = Color(0xFF171D1D)
val SurfaceVariantLight = Color(0xFFDAE5E3)
val OnSurfaceVariantLight = Color(0xFF3F4947)
val OutlineLight = Color(0xFF6F7978)
val OutlineVariantLight = Color(0xFFC3CDCB)
val InverseSurfaceLight = Color(0xFF2C3131)
val InverseOnSurfaceLight = Color(0xFFEEF1F1)
val InversePrimaryLight = Color(0xFF82D4D2)
val SurfaceBrightLight = Color(0xFFF7F9F9)
val SurfaceDimLight = Color(0xFFD7DBDA)
val SurfaceContainerLowestLight = Color(0xFFFFFFFF)
val SurfaceContainerLowLight = Color(0xFFF1F4F3)
val SurfaceContainerLight = Color(0xFFEBEEEE)
val SurfaceContainerHighLight = Color(0xFFE5E9E8)
val SurfaceContainerHighestLight = Color(0xFFE0E3E3)

// Dark: same near-black base, teal-tinted tonal surfaces instead of flat grey
val PrimaryDark = Color(0xFF82D4D2)
val OnPrimaryDark = Color(0xFF003736)
val PrimaryContainerDark = Color(0xFF00504F)
val OnPrimaryContainerDark = Color(0xFF9EF1EE)
val SecondaryDark = Color(0xFFB0CCCA)
val OnSecondaryDark = Color(0xFF1B3534)
val SecondaryContainerDark = Color(0xFF324B4A)
val OnSecondaryContainerDark = Color(0xFFCCE8E6)
val TertiaryDark = Color(0xFFA7CCE3)
val OnTertiaryDark = Color(0xFF0C3446)
val TertiaryContainerDark = Color(0xFF264B5E)
val OnTertiaryContainerDark = Color(0xFFC3E8FF)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF0E1514)
val OnBackgroundDark = Color(0xFFDDE4E3)
val SurfaceDark = Color(0xFF0E1514)
val OnSurfaceDark = Color(0xFFDDE4E3)
val SurfaceVariantDark = Color(0xFF3F4947)
val OnSurfaceVariantDark = Color(0xFFBFC9C7)
val OutlineDark = Color(0xFF899391)
val OutlineVariantDark = Color(0xFF3F4947)
val InverseSurfaceDark = Color(0xFFDDE4E3)
val InverseOnSurfaceDark = Color(0xFF2B3231)
val InversePrimaryDark = Color(0xFF00696A)
val SurfaceBrightDark = Color(0xFF333B3A)
val SurfaceDimDark = Color(0xFF0E1514)
val SurfaceContainerLowestDark = Color(0xFF091010)
val SurfaceContainerLowDark = Color(0xFF141D1C)
val SurfaceContainerDark = Color(0xFF182322)
val SurfaceContainerHighDark = Color(0xFF1F2C2B)
val SurfaceContainerHighestDark = Color(0xFF273534)

// Status colors. The text shades pass WCAG AA (>= 4.5:1) on the background and on
// their own 12% tint; the button gradients keep the icon above 3:1.
val ConnectedLight = Color(0xFF146C31)
val ConnectedTopLight = Color(0xFF2E9A4F)
val OnConnectedLight = Color(0xFFFFFFFF)
val ConnectingLight = Color(0xFF7F5000)

val ConnectedDark = Color(0xFF7DDC8F)
val ConnectedTopDark = Color(0xFFA6F0B6)
val OnConnectedDark = Color(0xFF00391A)
val ConnectingDark = Color(0xFFFFC266)
